# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmConfiguracio.ui'
#
# Created: Fri Dec 18 19:22:42 2009
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_configuracio(object):
    def setupUi(self, configuracio):
        configuracio.setObjectName("configuracio")
        configuracio.resize(648, 386)
        self.verticalLayout = QtGui.QVBoxLayout(configuracio)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtGui.QLabel(configuracio)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.cAddrServidor = QtGui.QLineEdit(configuracio)
        self.cAddrServidor.setObjectName("cAddrServidor")
        self.horizontalLayout_3.addWidget(self.cAddrServidor)
        self.bProvar = QtGui.QPushButton(configuracio)
        self.bProvar.setObjectName("bProvar")
        self.horizontalLayout_3.addWidget(self.bProvar)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.configServidor = QtGui.QTabWidget(configuracio)
        self.configServidor.setEnabled(True)
        self.configServidor.setObjectName("configServidor")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 9, 271, 261))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.cDispSerie = QtGui.QLineEdit(self.groupBox_2)
        self.cDispSerie.setMaximumSize(QtCore.QSize(146, 16777215))
        self.cDispSerie.setObjectName("cDispSerie")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cDispSerie)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.cVelocitat = QtGui.QComboBox(self.groupBox_2)
        self.cVelocitat.setEditable(True)
        self.cVelocitat.setObjectName("cVelocitat")
        self.cVelocitat.addItem("")
        self.cVelocitat.addItem("")
        self.cVelocitat.addItem("")
        self.cVelocitat.addItem("")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cVelocitat)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_15)
        self.cBits = QtGui.QSpinBox(self.groupBox_2)
        self.cBits.setMinimum(7)
        self.cBits.setMaximum(8)
        self.cBits.setObjectName("cBits")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cBits)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_16)
        self.cTimeout = QtGui.QSpinBox(self.groupBox_2)
        self.cTimeout.setObjectName("cTimeout")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cTimeout)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_17)
        self.cFabricant = QtGui.QLineEdit(self.groupBox_2)
        self.cFabricant.setObjectName("cFabricant")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cFabricant)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_18)
        self.cModel = QtGui.QLineEdit(self.groupBox_2)
        self.cModel.setObjectName("cModel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cModel)
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_19)
        self.cNumUnitat = QtGui.QLineEdit(self.groupBox_2)
        self.cNumUnitat.setObjectName("cNumUnitat")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.cNumUnitat)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(290, 10, 321, 261))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 78))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cTempsLectura = QtGui.QSpinBox(self.formLayoutWidget)
        self.cTempsLectura.setMinimum(10)
        self.cTempsLectura.setObjectName("cTempsLectura")
        self.horizontalLayout_5.addWidget(self.cTempsLectura)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_4.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_4.setItem(1, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cTempsGravacio = QtGui.QSpinBox(self.formLayoutWidget)
        self.cTempsGravacio.setMinimum(1)
        self.cTempsGravacio.setObjectName("cTempsGravacio")
        self.horizontalLayout_7.addWidget(self.cTempsGravacio)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.formLayout_4.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.configServidor.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.taulaParametres = QtGui.QTableWidget(self.tab)
        self.taulaParametres.setMinimumSize(QtCore.QSize(606, 0))
        self.taulaParametres.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.taulaParametres.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.taulaParametres.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.taulaParametres.setWordWrap(False)
        self.taulaParametres.setObjectName("taulaParametres")
        self.taulaParametres.setColumnCount(7)
        self.taulaParametres.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(6, item)
        self.taulaParametres.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.taulaParametres)
        self.configServidor.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.configServidor)
        self.buttonBar = QtGui.QDialogButtonBox(configuracio)
        self.buttonBar.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBar.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBar.setObjectName("buttonBar")
        self.verticalLayout.addWidget(self.buttonBar)

        self.retranslateUi(configuracio)
        self.configServidor.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBar, QtCore.SIGNAL("accepted()"), configuracio.accept)
        QtCore.QObject.connect(self.buttonBar, QtCore.SIGNAL("rejected()"), configuracio.reject)
        QtCore.QMetaObject.connectSlotsByName(configuracio)

    def retranslateUi(self, configuracio):
        configuracio.setWindowTitle(QtGui.QApplication.translate("configuracio", "Configuració", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("configuracio", "Servidor de lectures", None, QtGui.QApplication.UnicodeUTF8))
        self.bProvar.setText(QtGui.QApplication.translate("configuracio", "Provar!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("configuracio", "Comunicacions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("configuracio", "Port serie:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("configuracio", "Velocitat:", None, QtGui.QApplication.UnicodeUTF8))
        self.cVelocitat.setItemText(0, QtGui.QApplication.translate("configuracio", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.cVelocitat.setItemText(1, QtGui.QApplication.translate("configuracio", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.cVelocitat.setItemText(2, QtGui.QApplication.translate("configuracio", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.cVelocitat.setItemText(3, QtGui.QApplication.translate("configuracio", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("configuracio", "Bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("configuracio", "Timeout:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("configuracio", "Fabricant:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("configuracio", "Model:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("configuracio", "Número d\'unitat:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("configuracio", "Captura de dades", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("configuracio", "Segons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("configuracio", "Interval de gravació", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("configuracio", "Minuts", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("configuracio", "Temps de lectura", None, QtGui.QApplication.UnicodeUTF8))
        self.configServidor.setTabText(self.configServidor.indexOf(self.tab_2), QtGui.QApplication.translate("configuracio", "Generals", None, QtGui.QApplication.UnicodeUTF8))
        self.taulaParametres.setSortingEnabled(True)
        self.taulaParametres.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("configuracio", "Cons?", None, QtGui.QApplication.UnicodeUTF8))
        self.taulaParametres.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("configuracio", "Abreviació", None, QtGui.QApplication.UnicodeUTF8))
        self.taulaParametres.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("configuracio", "Registre", None, QtGui.QApplication.UnicodeUTF8))
        self.taulaParametres.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("configuracio", "Núm. Valors", None, QtGui.QApplication.UnicodeUTF8))
        self.taulaParametres.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("configuracio", "Descripció", None, QtGui.QApplication.UnicodeUTF8))
        self.taulaParametres.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("configuracio", "Escala", None, QtGui.QApplication.UnicodeUTF8))
        self.taulaParametres.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("configuracio", "Valor màxim", None, QtGui.QApplication.UnicodeUTF8))
        self.configServidor.setTabText(self.configServidor.indexOf(self.tab), QtGui.QApplication.translate("configuracio", "Paràmetres", None, QtGui.QApplication.UnicodeUTF8))

