# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\frmConfiguracioSrv.ui'
#
# Created: Sat May 19 18:36:55 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_configuracio(object):
    def setupUi(self, configuracio):
        configuracio.setObjectName(_fromUtf8("configuracio"))
        configuracio.resize(1002, 644)
        self.verticalLayout = QtGui.QVBoxLayout(configuracio)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_38 = QtGui.QLabel(configuracio)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_16.addWidget(self.label_38)
        self.cAddrServidor = QtGui.QLineEdit(configuracio)
        self.cAddrServidor.setObjectName(_fromUtf8("cAddrServidor"))
        self.horizontalLayout_16.addWidget(self.cAddrServidor)
        self.bProvar = QtGui.QPushButton(configuracio)
        self.bProvar.setObjectName(_fromUtf8("bProvar"))
        self.horizontalLayout_16.addWidget(self.bProvar)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.splitter = QtGui.QSplitter(configuracio)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeDevices = QtGui.QTreeWidget(self.splitter)
        self.treeDevices.setObjectName(_fromUtf8("treeDevices"))
        self.confDispositu = QtGui.QTabWidget(self.splitter)
        self.confDispositu.setObjectName(_fromUtf8("confDispositu"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.groupBox_7)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.cModel = QtGui.QLineEdit(self.groupBox_7)
        self.cModel.setObjectName(_fromUtf8("cModel"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.cModel)
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.cNumUnitat = QtGui.QLineEdit(self.groupBox_7)
        self.cNumUnitat.setObjectName(_fromUtf8("cNumUnitat"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.cNumUnitat)
        self.cFabricant_4 = QtGui.QLineEdit(self.groupBox_7)
        self.cFabricant_4.setObjectName(_fromUtf8("cFabricant_4"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.cFabricant_4)
        self.horizontalLayout.addLayout(self.formLayout_8)
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.cTempsLectura_4 = QtGui.QSpinBox(self.groupBox_7)
        self.cTempsLectura_4.setMinimum(10)
        self.cTempsLectura_4.setObjectName(_fromUtf8("cTempsLectura_4"))
        self.horizontalLayout_14.addWidget(self.cTempsLectura_4)
        self.label_34 = QtGui.QLabel(self.groupBox_7)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_14.addWidget(self.label_34)
        self.formLayout_7.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_14)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_7.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_7.setItem(1, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.label_35 = QtGui.QLabel(self.groupBox_7)
        self.label_35.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_35)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.cTempsGravacio_4 = QtGui.QSpinBox(self.groupBox_7)
        self.cTempsGravacio_4.setMinimum(1)
        self.cTempsGravacio_4.setObjectName(_fromUtf8("cTempsGravacio_4"))
        self.horizontalLayout_15.addWidget(self.cTempsGravacio_4)
        self.label_36 = QtGui.QLabel(self.groupBox_7)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_15.addWidget(self.label_36)
        self.formLayout_7.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.label_37 = QtGui.QLabel(self.groupBox_7)
        self.label_37.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_37)
        self.horizontalLayout.addLayout(self.formLayout_7)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.cDispSerie = QtGui.QLineEdit(self.groupBox_2)
        self.cDispSerie.setMaximumSize(QtCore.QSize(146, 16777215))
        self.cDispSerie.setObjectName(_fromUtf8("cDispSerie"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cDispSerie)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.cVelocitat = QtGui.QComboBox(self.groupBox_2)
        self.cVelocitat.setEditable(True)
        self.cVelocitat.setObjectName(_fromUtf8("cVelocitat"))
        self.cVelocitat.addItem(_fromUtf8(""))
        self.cVelocitat.addItem(_fromUtf8(""))
        self.cVelocitat.addItem(_fromUtf8(""))
        self.cVelocitat.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cVelocitat)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_15)
        self.cBits = QtGui.QSpinBox(self.groupBox_2)
        self.cBits.setMinimum(7)
        self.cBits.setMaximum(8)
        self.cBits.setObjectName(_fromUtf8("cBits"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cBits)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_16)
        self.cTimeout = QtGui.QSpinBox(self.groupBox_2)
        self.cTimeout.setObjectName(_fromUtf8("cTimeout"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cTimeout)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.confDispositu.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.taulaParametres = QtGui.QTableWidget(self.tab_2)
        self.taulaParametres.setMinimumSize(QtCore.QSize(606, 0))
        self.taulaParametres.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.taulaParametres.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.taulaParametres.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.taulaParametres.setWordWrap(False)
        self.taulaParametres.setObjectName(_fromUtf8("taulaParametres"))
        self.taulaParametres.setColumnCount(7)
        self.taulaParametres.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.taulaParametres.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.taulaParametres.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.taulaParametres.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.taulaParametres.setHorizontalHeaderItem(6, item)
        self.taulaParametres.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.taulaParametres)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.confDispositu.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtGui.QDialogButtonBox(configuracio)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(configuracio)
        self.confDispositu.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), configuracio.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), configuracio.reject)
        QtCore.QMetaObject.connectSlotsByName(configuracio)

    def retranslateUi(self, configuracio):
        configuracio.setWindowTitle(QtGui.QApplication.translate("configuracio", "Configuració del servidor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("configuracio", "Servidor de lectures", None, QtGui.QApplication.UnicodeUTF8))
        self.bProvar.setText(QtGui.QApplication.translate("configuracio", "Provar!", None, QtGui.QApplication.UnicodeUTF8))
        self.treeDevices.headerItem().setText(0, QtGui.QApplication.translate("configuracio", "Dispositius", None, QtGui.QApplication.UnicodeUTF8))
        self.treeDevices.headerItem().setText(1, QtGui.QApplication.translate("configuracio", "Habilitat", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("configuracio", "Paràmetres Generals Analitzador", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("configuracio", "Fabricant:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("configuracio", "Model:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("configuracio", "Número d\'unitat:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("configuracio", "Segons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("configuracio", "Interval de gravació", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("configuracio", "Minuts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("configuracio", "Temps de lectura", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("configuracio", "Comunicacions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("configuracio", "Port serie:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("configuracio", "Velocitat:", None, QtGui.QApplication.UnicodeUTF8))
        self.cVelocitat.setItemText(0, QtGui.QApplication.translate("configuracio", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.cVelocitat.setItemText(1, QtGui.QApplication.translate("configuracio", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.cVelocitat.setItemText(2, QtGui.QApplication.translate("configuracio", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.cVelocitat.setItemText(3, QtGui.QApplication.translate("configuracio", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("configuracio", "Bits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("configuracio", "Timeout:", None, QtGui.QApplication.UnicodeUTF8))
        self.confDispositu.setTabText(self.confDispositu.indexOf(self.tab), QtGui.QApplication.translate("configuracio", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.taulaParametres.setSortingEnabled(True)
        item = self.taulaParametres.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("configuracio", "Cons?", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taulaParametres.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("configuracio", "Abreviació", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taulaParametres.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("configuracio", "Registre", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taulaParametres.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("configuracio", "Núm. Valors", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taulaParametres.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("configuracio", "Descripció", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taulaParametres.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("configuracio", "Escala", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taulaParametres.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("configuracio", "Valor màxim", None, QtGui.QApplication.UnicodeUTF8))
        self.confDispositu.setTabText(self.confDispositu.indexOf(self.tab_2), QtGui.QApplication.translate("configuracio", "Paràmetres", None, QtGui.QApplication.UnicodeUTF8))

