# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\frmPrincipal.ui'
#
# Created: Sat May 19 01:26:07 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_finestraPrincipal(object):
    def setupUi(self, finestraPrincipal):
        finestraPrincipal.setObjectName(_fromUtf8("finestraPrincipal"))
        finestraPrincipal.resize(1161, 812)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(finestraPrincipal.sizePolicy().hasHeightForWidth())
        finestraPrincipal.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(finestraPrincipal)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.arbreAnalitzadors = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arbreAnalitzadors.sizePolicy().hasHeightForWidth())
        self.arbreAnalitzadors.setSizePolicy(sizePolicy)
        self.arbreAnalitzadors.setMinimumSize(QtCore.QSize(256, 0))
        self.arbreAnalitzadors.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.arbreAnalitzadors.setAutoExpandDelay(1)
        self.arbreAnalitzadors.setUniformRowHeights(True)
        self.arbreAnalitzadors.setObjectName(_fromUtf8("arbreAnalitzadors"))
        self.splitter_2 = QtGui.QSplitter(self.splitter)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tabWidget = QtGui.QTabWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.zonaDisplays = QtGui.QMdiArea(self.tab)
        self.zonaDisplays.setObjectName(_fromUtf8("zonaDisplays"))
        self.verticalLayout_7.addWidget(self.zonaDisplays)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.splitter)
        finestraPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(finestraPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fitxer = QtGui.QMenu(self.menubar)
        self.menu_Fitxer.setObjectName(_fromUtf8("menu_Fitxer"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        self.menuLector = QtGui.QMenu(self.menubar)
        self.menuLector.setObjectName(_fromUtf8("menuLector"))
        finestraPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(finestraPrincipal)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        finestraPrincipal.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(finestraPrincipal)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        finestraPrincipal.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSobre_el_programa = QtGui.QAction(finestraPrincipal)
        self.actionSobre_el_programa.setObjectName(_fromUtf8("actionSobre_el_programa"))
        self.actionConfiguracio = QtGui.QAction(finestraPrincipal)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Icones/preferencies.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfiguracio.setIcon(icon)
        self.actionConfiguracio.setObjectName(_fromUtf8("actionConfiguracio"))
        self.actionSortir = QtGui.QAction(finestraPrincipal)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Icones/sortir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSortir.setIcon(icon1)
        self.actionSortir.setObjectName(_fromUtf8("actionSortir"))
        self.actionIniciar = QtGui.QAction(finestraPrincipal)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Icones/iniciarCaptura.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIniciar.setIcon(icon2)
        self.actionIniciar.setObjectName(_fromUtf8("actionIniciar"))
        self.actionAturar = QtGui.QAction(finestraPrincipal)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Icones/aturarCaptura.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAturar.setIcon(icon3)
        self.actionAturar.setObjectName(_fromUtf8("actionAturar"))
        self.actionIniciar_servei = QtGui.QAction(finestraPrincipal)
        self.actionIniciar_servei.setObjectName(_fromUtf8("actionIniciar_servei"))
        self.actionConnectar = QtGui.QAction(finestraPrincipal)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Icones/connectar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectar.setIcon(icon4)
        self.actionConnectar.setObjectName(_fromUtf8("actionConnectar"))
        self.actionDesconnectar = QtGui.QAction(finestraPrincipal)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Icones/desconnectar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDesconnectar.setIcon(icon5)
        self.actionDesconnectar.setObjectName(_fromUtf8("actionDesconnectar"))
        self.actionExportaGrafiques = QtGui.QAction(finestraPrincipal)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Icones/guardar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportaGrafiques.setIcon(icon6)
        self.actionExportaGrafiques.setObjectName(_fromUtf8("actionExportaGrafiques"))
        self.actionExportaHistoric = QtGui.QAction(finestraPrincipal)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Icones/llibreta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportaHistoric.setIcon(icon7)
        self.actionExportaHistoric.setObjectName(_fromUtf8("actionExportaHistoric"))
        self.actionBuidaLectures = QtGui.QAction(finestraPrincipal)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icones/Icones/buidar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuidaLectures.setIcon(icon8)
        self.actionBuidaLectures.setObjectName(_fromUtf8("actionBuidaLectures"))
        self.actionFor_ar_lectura = QtGui.QAction(finestraPrincipal)
        self.actionFor_ar_lectura.setObjectName(_fromUtf8("actionFor_ar_lectura"))
        self.menu_Fitxer.addAction(self.actionExportaHistoric)
        self.menu_Fitxer.addAction(self.actionExportaGrafiques)
        self.menu_Fitxer.addAction(self.actionConfiguracio)
        self.menu_Fitxer.addSeparator()
        self.menu_Fitxer.addAction(self.actionSortir)
        self.menuAjuda.addAction(self.actionSobre_el_programa)
        self.menuLector.addAction(self.actionConnectar)
        self.menuLector.addAction(self.actionDesconnectar)
        self.menuLector.addSeparator()
        self.menuLector.addAction(self.actionAturar)
        self.menuLector.addAction(self.actionIniciar)
        self.menuLector.addAction(self.actionFor_ar_lectura)
        self.menuLector.addSeparator()
        self.menuLector.addAction(self.actionBuidaLectures)
        self.menuLector.addSeparator()
        self.menubar.addAction(self.menu_Fitxer.menuAction())
        self.menubar.addAction(self.menuLector.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.toolBar.addAction(self.actionSortir)
        self.toolBar.addAction(self.actionConfiguracio)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnectar)
        self.toolBar.addAction(self.actionDesconnectar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIniciar)
        self.toolBar.addAction(self.actionAturar)

        self.retranslateUi(finestraPrincipal)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionSortir, QtCore.SIGNAL(_fromUtf8("triggered()")), finestraPrincipal.close)
        QtCore.QMetaObject.connectSlotsByName(finestraPrincipal)

    def retranslateUi(self, finestraPrincipal):
        finestraPrincipal.setWindowTitle(QtGui.QApplication.translate("finestraPrincipal", "VisorLector 2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.arbreAnalitzadors.setSortingEnabled(True)
        self.arbreAnalitzadors.headerItem().setText(0, QtGui.QApplication.translate("finestraPrincipal", "Analitzador", None, QtGui.QApplication.UnicodeUTF8))
        self.arbreAnalitzadors.headerItem().setText(1, QtGui.QApplication.translate("finestraPrincipal", "Descripció", None, QtGui.QApplication.UnicodeUTF8))
        self.arbreAnalitzadors.headerItem().setText(2, QtGui.QApplication.translate("finestraPrincipal", "Mostrar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("finestraPrincipal", "Valors instantànis", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("finestraPrincipal", "Històric", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Fitxer.setTitle(QtGui.QApplication.translate("finestraPrincipal", "&Fitxer", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAjuda.setTitle(QtGui.QApplication.translate("finestraPrincipal", "Ajuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLector.setTitle(QtGui.QApplication.translate("finestraPrincipal", "Lector", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("finestraPrincipal", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSobre_el_programa.setText(QtGui.QApplication.translate("finestraPrincipal", "Sobre el programa...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfiguracio.setText(QtGui.QApplication.translate("finestraPrincipal", "Configuració", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSortir.setText(QtGui.QApplication.translate("finestraPrincipal", "Sortir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIniciar.setText(QtGui.QApplication.translate("finestraPrincipal", "Iniciar captura", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAturar.setText(QtGui.QApplication.translate("finestraPrincipal", "&Pausar captura", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIniciar_servei.setText(QtGui.QApplication.translate("finestraPrincipal", "Iniciar servei", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectar.setText(QtGui.QApplication.translate("finestraPrincipal", "Connectar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesconnectar.setText(QtGui.QApplication.translate("finestraPrincipal", "Desconnectar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportaGrafiques.setText(QtGui.QApplication.translate("finestraPrincipal", "Exporta &Gràfiques", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportaHistoric.setText(QtGui.QApplication.translate("finestraPrincipal", "Exporta H&istòric Local", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuidaLectures.setText(QtGui.QApplication.translate("finestraPrincipal", "Buida lectures locals", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFor_ar_lectura.setText(QtGui.QApplication.translate("finestraPrincipal", "Forçar lectura", None, QtGui.QApplication.UnicodeUTF8))

import recursos_rc
