# -*- coding: utf-8 -*-

cmdsCVMk = {
            "TPF": {"registre"  : "RVI",
                    "numRegs"   : 4,
                    "descripcio": u"Tensió simple instantània",  
                    "valEscala" : 1,
                    "numDigits" : 9 },

            "RVM": {"registre"  : "RVM",
                    "numRegs"   : 3,
                    "descripcio": u"Tensió simple màxima",   
                    "valEscala" : 1, 
                    "numDigits" : 9 },

            "RVm": {"registre"  : "RVm", 
                    "numRegs"   : 3,
		    "descVars"  : ['R','S','T'],
                    "magnitut"  : 'V', 
                    "descripcio": u"Tensió simple mínima",   
                    "valEscala" : 1, 
                    "numDigits" : 9 },

            "ROI": {"registre"  : "ROI",
                    "numRegs"   : 4,
                    "descripcio": u"Tensió composta instantània", 
                    "valEscala" : 1, 
                    "numDigits" : 9 },

            "ROM": {"registre"  : "ROM", 
                    "numRegs"   : 4, 
                    "descripcio": u"Tensió composta màxima",  
                    "valEscala" : 1, 
                    "numDigits" : 9 }, 

            "IPF": {"registre"  : "RAI", 
                    "numRegs"   : 4, 
                    "descripcio": u"Intensitat instantània",  
                    "valEscala" : 0.001, 
                    "numDigits" : 9 }, 

            "RAM": {"registre"  : "RAM",
                    "numRegs"   : 3,  
                    "descripcio": u"Intensitat màxima",  
                    "valEscala" : 0.001,
                    "numDigits" : 9 },
            
            "RAm": {"registre"  : "RAm",
                    "numRegs"   : 3,  
                    "descripcio": u"Intensitat mínima",  
                    "valEscala" : 0.001,
                    "numDigits" : 9 },
            
            "PAT": {"registre"  : "RPI",
                    "numRegs"   : 4,  
                    "descripcio": u"Potència activa instantània",  
                    "valEscala" : 0.001,
                    "numDigits" : 9 },

            "RPM": {"registre"  : "RPM",
                    "numRegs"   : 4,  
                    "descripcio": u"Potència activa màxima",  
                    "valEscala" : 1,
                    "numDigits" : 9 },

            "RPm": {"registre"  : "RPm",
                    "numRegs"   : 4,  
                    "descripcio": u"Potència activa mínima",  
                    "valEscala" : 1,
                    "numDigits" : 9 },

            "RLI": {"registre"  : "RLI",
                    "numRegs"   : 4,  
                    "descripcio": u"Potència inductiva instantània",  
                    "valEscala" : 0.001,
                    "numDigits" : 9 },
            
            "RLM": {"registre"  : "RLM",
                    "numRegs"   : 4,  
                    "descripcio": u"Potència inductiva màxima",  
                    "valEscala" : 1,
                    "numDigits" : 9 },

            "RLm": {"registre"  : "RLm",
                    "numRegs"   : 4,  
                    "descripcio": u"Potència inductiva mínima",  
                    "valEscala" : 1,
                    "numDigits" : 9 },

            "RCI": {"registre"  : "RCI",
                    "numRegs"   : 4,  
                    "descripcio": u"Potència capacitiva instantània",  
                    "valEscala" : 0.001,
                    "numDigits" : 9 },
                    
            "RCM": {"registre"  : "RCM",
                    "numRegs"   : 3,  
                    "descripcio": u"Potència capacitiva màxima",  
                    "valEscala" : 1,
                    "numDigits" : 9 },

            "RCm": {"registre"  : "RCm",
                    "numRegs"   : 3,  
                    "descripcio": u"Potència capacitiva mínima",  
                    "valEscala" : 1,
                    "numDigits" : 9 },
                    
            "FPT": {"registre"  : "RFI",
                    "numRegs"   : 4, 
		    "descVars"  : ['R','S','T','FPm'],
		    "magnitut"  : '',   
                    "descripcio": u"Factor potència instantàni",  
                    "valEscala" : 0.01,
                    "numDigits" : 3 },

            "RFM": {"registre"  : "RFM",
                    "numRegs"   : 3,  
                    "descripcio": u"Factor potència màxim",  
                    "valEscala" : 0.01,
                    "numDigits" : 3 },
            
            "RFm": {"registre"  : "RFm",
                    "numRegs"   : 3,  
                    "descripcio": u"Factor potència mínima",  
                    "valEscala" : 0.01,
                    "numDigits" : 3 },   

            "FRE": {"registre"  : "RHI",
                    "numRegs"   : 1,  
                    "descripcio": u"Freqüència instantània",  
                    "valEscala" : 0.1,
                    "numDigits" : 3 },

            "RHM": {"registre"  : "RHM",
                    "numRegs"   : 1,  
                    "descripcio": u"Freqüència màxima",  
                    "valEscala" : 0.1,
                    "numDigits" : 3 },
            
            "RHm": {"registre"  : "RHm",
                    "numRegs"   : 1,  
                    "descripcio": u"Freqüència mínima",  
                    "valEscala" : 0.1,
                    "numDigits" : 3 }
}     
